---

   disable_firewall: true
   oracle_sysctl:
      - { name: kernel.shmall, value: 4294967296 }
      - { name: kernel.shmmax, value: 68719476736 }
      - { name: kernel.shmmni, value: 4096 }
      - { name: kernel.sem, value: "250 32000 100 128" }
      - { name: fs.file-max, value: 6815744 }
      - { name: fs.aio-max-nr, value: 3145728 }
      - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
      - { name: net.core.rmem_default, value: 262144 }
      - { name: net.core.rmem_max, value: 4194304 }
      - { name: net.core.wmem_default, value: 262144 }
      - { name: net.core.wmem_max, value: 1048576 }
      - { name: kernel.panic_on_oops, value: 1 }
      - { name: vm.min_free_kbytes, value: 524288 }
   oracle_groups:
      - { group: asmdba, gid: 54318 }
      - { group: asmoper, gid: 54319 }
      - { group: asmadmin, gid: 54320 }
      - { group: oinstall, gid: 54321 }
      - { group: dba, gid: 54322 }
      - { group: backupdba, gid: 54323 }
      - { group: oper, gid: 54324 }
      - { group: dgdba, gid: 54325 }
      - { group: kmdba, gid: 54326 }
   oracle_users:         # Passwd :Oracle123
      - { username: oracle, uid: 54321, primgroup: oinstall, othergroups: "dba,asmadmin,asmdba,backupdba,dgdba,kmdba,oper", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }
   grid_users:
      - { username: grid, uid: 54320, primgroup: oinstall, othergroups: "asmadmin,asmdba,asmoper,dba", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }

   oracle_install_group: oracle
   oracle_user         : oracle
   grid_user           : grid
   oracle_user_home    : "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
   grid_user_home      : "/home/{{ grid_install_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
   oracle_group        : oinstall    #  # Primary group for oracle_user.
   oracle_rsp_stage    : "{{ oracle_stage }}/rsp"

   oper_group          : oper
   dba_group           : dba
   asmoper_group       : asmoper
   asmdba_group        : asmdba
   asmadmin_group      : asmadmin
   soft_no_file        : 4096
   hard_no_file        : 65536
   soft_nproc          : 16384
   hard_nproc          : 16384
   soft_stack          : 10240
   hard_stack          : 32768
   soft_memlock        : "{{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}"
   hard_memlock        : "{{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}"
   configure_cluster   : false

   oracle_group        : oinstall
   grid_install_user   : grid
   oracle_base         : "{{ lookup('ini', 'oracle_base             section=standalone_asm       file=/tmp/info.ini') }}"
   oracle_inventory_loc: "{{ lookup('ini', 'oracle_inventory_loc    section=standalone_asm       file=/tmp/info.ini') }}"
   oracle_inventory    : "{{ lookup('ini', 'oracle_inventory        section=standalone_asm       file=/tmp/info.ini') }}"
   oracle_stage        : "{{ lookup('ini', 'oracle_stage            section=standalone_asm       file=/tmp/info.ini') }}"
   oracle_home_gi      : "{{ lookup('ini', 'oracle_home_gi          section=standalone_asm       file=/tmp/info.ini') }}"
   oracle_home_db      : "{{ lookup('ini', 'oracle_home_db          section=standalone_asm       file=/tmp/info.ini') }}"

   oracle_profile_name  : ".profile_{{oracle_user}}"
   disable_selinux      : true
   oracle_directories:

          - {name: "{{ oracle_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_rsp_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_inventory_loc}}", owner: "{{ grid_install_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_inventory}}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/cfgtoollogs", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/admin", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/audit", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/cfgtoollogs/dbca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/cfgtoollogs/sqlpatch", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }

          - {name: "{{ oracle_base }}/cfgtoollogs/netca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }




