---

- name: install-home-db | copy Binary to destinations
  copy: src=/home/config/{{ item }} dest={{ oracle_stage }} owner=oracle group=oinstall mode=775
  with_items:
        - linuxx64_12201_database.zip
  tags:
        - oradbsw
  register: sadbswcopy
- debug:
        var: sadbswcopy

- name: install-home-db | Unzip Binary
  action: shell unzip -oq  {{ oracle_stage }}/{{ item }}  -d {{ oracle_stage }}
  with_items:
          - linuxx64_12201_database.zip
  become: yes
  become_user: "{{ oracle_user }}"
  ignore_errors: yes
  tags:
          - oradbswunpack

- name: remove gi software
  command: rm -rf  {{ oracle_stage }}/{{ item }}
  with_items:
      - linuxx64_12201_database.zip
  become_user: grid_install_user
  tags:
        - removegisw

- name: install-home-db | Check if DB-server is already installed
  shell: cat "{{ oracle_inventory_loc }}/ContentsXML/inventory.xml" |grep -w {{ oracle_home_db  }} |awk  '{print $3}' | cut -f2 -d'"'
  run_once: "{{ configure_cluster }}"
  register: existing_dbhome
  changed_when: False
  failed_when: False
  tags: install_home,existing_dbhome,checkdbswinstall

- debug: msg="Installing ORACLE_HOME - {{ oracle_home_db }}"
  when: oracle_home_db not in existing_dbhome.stdout_lines

- name: install-home-db | add dotprofile
  template:
      src: dotprofile-home.j2
      dest: "/home/{{ oracle_user}}/{{ oracle_profile_name}}"
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      mode: 0660
  ignore_errors: yes
  when: oracle_home_db not in existing_dbhome.stdout_lines
  tags: create_db,dotprofile_db

- name: copy of SADBSW responsefile
  copy: src=/home/config/oracle_12.2.0.1.rsp dest={{ oracle_rsp_stage }}  owner=oracle group=oinstall mode=775
  tags: sadbswrsp copy
  register: sadbswrspcpy
- debug:
     var: sadbswrspcpy


- name: install oracle 12.2.0.1
  command: "{{ oracle_stage }}/database/runInstaller -responseFile {{ oracle_rsp_stage }}/'oracle_12.2.0.1.rsp' -ignorePrereq -ignoreSysPrereqs -silent -waitforcompletion"
  become: yes
  become_user: oracle
  #  ignore_errors: yes
  register: installdbsoftware
  tags:
     -dbswinstall
- debug:
        var: installdbsoftware

- name: install-home-db | Run root script after installation
  shell: "{{ oracle_home_db }}/root.sh"
  run_once: "{{ configure_cluster}}"
  #  ignore_errors: yes
  tags:
    - runroot
  register: rootsh
- debug:
     var: rootsh
